Models/ApplicationUser.cs
using Microsoft.AspNetCore.Identity;
using SahayogNepal.Models.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SahayogNepal.Models
{
    public class ApplicationUser:IdentityUser
    {
        public UserType UserType { get; set; }
    }
}

Models/Donor.cs
using SahayogNepal.Models.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SahayogNepal.Models
{
    public class Donor
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime? RecoveredDate { get; set; }
        public string MobileNumber { get; set; }
        public Gender  Gender { get; set; }
        public string City { get; set; }
        public string BloodGroup { get; set; }
        public float Age { get; set; }
        public bool HasDischargeReport { get; set; }
    }
}

Models/DonorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SahayogNepal.Models
{
    public class DonorViewModel
    {
        public string name { get; set; }
        public double mobile { get; set; }
        public string[] gender { get; set; }
        public bool discharge { get; set; }
        public string city { get; set; }
        public string recoveredDate { get; set; }
        public string[] blood { get; set; }
        public float age { get; set; }
    }
}

Models/Enums/Gender.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SahayogNepal.Models.Enums
{
    public enum Gender
    {
        male,
        female,
        other
    }
}

Models/Enums/UserType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SahayogNepal.Models.Enums
{
    public enum UserType
    {
        Donor,
        Patient
    }
}

Models/ErrorViewModel.cs
using System;

namespace SahayogNepal.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Patient.cs
using SahayogNepal.Models.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SahayogNepal.Models
{
    public class Patient
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string MobileNumber { get; set; }
        public float Age { get; set; }
        public Gender  Gender { get; set; }
        public string City { get; set; }
        public string BloodGroup { get; set; }
        public string Hospital { get; set; }
        public bool HasCaseSheet { get; set; }
        public DateTime RegisteredDate { get; set; }
    }
}

Models/ViewModels/DonorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SahayogNepal.Models.ViewModels
{
    public class DonorViewModel
    {
        public string name { get; set; }
        public string mobile { get; set; }
        public string gender { get; set; }
        public bool discharge { get; set; }
        public string city { get; set; }
        public string recoveredDate { get; set; }
        public string blood { get; set; }
        public float age { get; set; }
    }
}

Models/ViewModels/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SahayogNepal.Models.ViewModels
{
    public class HomeViewModel
    {
        public int Donors;
        public int Patients;
    }
}

Models/ViewModels/PatientViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SahayogNepal.Models.ViewModels
{
    public class PatientViewModel
    {
        public string name { get; set; }
        public string mobile { get; set; }
        public float age { get; set; }
        public string gender { get; set; }
        public string city { get; set; }
        public string blood { get; set; }
        public string hospital { get; set; }
        public bool hasCaseSheet { get; set; }
    }
}

Controllers/DonorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SahayogNepal.Interface;
using SahayogNepal.Models;
using SahayogNepal.Models.ViewModels;

namespace SahayogNepal.Controllers
{
    public class DonorController : Controller
    {
        private readonly SahayogNepal.Interface.IDonorService donorService;

        public DonorController(IDonorService donorService)
        {
            this.donorService = donorService;
        }

        public IActionResult Index()
        {
            return View();
        }
        public async Task<bool> SubmitData(DonorViewModel donorData)
        {
            return await donorService.AddDonor(donorData);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SahayogNepal.Interface;
using SahayogNepal.Models;
using SahayogNepal.Models.ViewModels;

namespace SahayogNepal.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IPatientService patientService;

        private readonly IDonorService donorService;

        public HomeController(ILogger<HomeController> logger, IPatientService patientService, IDonorService donorService) 
        {
            this.patientService = patientService;
            this.donorService = donorService;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            var model = new HomeViewModel
            {
                Donors = await donorService.TotalDonor(),
                Patients = await patientService.TotalPatient()
            };
            return View(model);
        }
        [HttpGet("plasma-therapy")]
        public IActionResult PlasmaTherapy()
        {
            return View();
        }
        [HttpGet("sahayogi-haat")]
        public IActionResult SahayogiHaath()
        {
            return View();
        }
        //public IActionResult Privacy()
        //{
        //    return View();
        //}

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PatientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SahayogNepal.Interface;
using SahayogNepal.Models.ViewModels;

namespace SahayogNepal.Controllers
{
    public class PatientController : Controller
    {
        private readonly IPatientService patientService;

        public PatientController(IPatientService PatientService)
        {
            this.patientService = PatientService;
        }

        public IActionResult Index()
        {
            return View();
        }
        public async Task<bool> SubmitPatientData(PatientViewModel PatientData)
        {
            return await patientService.AddPatient(PatientData);
        }
    }
}

Views/Donor/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<style>
    #cf-context {
        width: 70vw;
        height: 70vh;
    }
    #form {
        height: 0px;
        overflow: hidden;
    }
</style>
<div class="container">
   
    <form id="form" cf-form method="post" asp-controller="Donor" asp-action="SubmitData">
        <cf-robot-message cf-questions="Filling out this form will only take 2 minutes and it could save someone's life.
We will not ask you for any information we do not need."></cf-robot-message>

        <input cf-questions="Did you ever get Covid? " cf-label="Yes" type="radio" value="0">
        <input type="text" name="name" cf-questions="What is your name?">
        <input type="number" name="mobile" cf-questions="What is your mobile number?">
        <input type="number" name="age" cf-questions="How old are you?">
        <input cf-questions="What's your gender?" type="radio" name="gender" value="female" cf-label="female">
        <input type="radio" name="gender" value="male" cf-label="male">
        <input type="radio" name="gender" value="other" cf-label="other">
        <input type="text" name="city" cf-questions="What is your current address?">
        <input cf-questions="What's your blood group?" type="radio" name="blood" value="A+" cf-label="A+">
        <input type="radio" name="blood" value="A-" cf-label="A-">
        <input type="radio" name="blood" value="B+" cf-label="B+">
        <input type="radio" name="blood" value="B-" cf-label="B-">
        <input type="radio" name="blood" value="O+" cf-label="O+">
        <input type="radio" name="blood" value="O-" cf-label="O-">
        <input type="radio" name="blood" value="AB+" cf-label="AB+">
        <input type="radio" name="blood" value="AB-" cf-label="AB-">
        <input type="text" name="recoveredDate" cf-questions="What was your date of recovery? (mm/dd/yyyy)">
        <input cf-questions="Do you have a discharge report from the hospital?" type="radio" name="discharge" value="Yes" cf-label="Yes">
        <input type="radio" name="discharge" value="NotYet" cf-label="Not Yet">
        <cf-robot-message cf-questions="By submitting this form"></cf-robot-message>
        <cf-robot-message cf-questions="I confirm that the information I have provided in here is complete and accurate to the best of my knowledge."></cf-robot-message>
        <cf-robot-message cf-questions="I confirm that I wish to share the information provided in here for the exclusive purpose(s) of matching with patients from the database of patients registered with sahayogNepal and sharing this information directly and solely with the [matched patients and/or their next of-kin."></cf-robot-message>
        <input cf-questions=Confirmation? name="confirm" cf-label="Yes submit by data" type="radio" value="0">

    </form>
    <div id="cf-context" role="cf-context" cf-context></div>
    <!-- partial -->

</div>
<script src='https://cdn.jsdelivr.net/gh/space10-community/conversational-form@latest/dist/conversational-form.min.js'></script>
<script>
    window.onload = function () {
        var conversationalForm = window.cf.ConversationalForm.startTheConversation({
            formEl: document.getElementById("form"),
            context: document.getElementById("cf-context"),
            submitCallback: function () {
                var formData = conversationalForm.getFormData();
                var formDataSerialized = conversationalForm.getFormData(true);
                console.log("Formdata:", formData);
                console.log("Formdata, serialized:", formDataSerialized);
                $.post("/donor/submitData/", { donorData: formDataSerialized })
                    .done(function () {
                        conversationalForm.addRobotChatResponse("Thank you, you have completed your registration");
                    }).fail(function () {
                        conversationalForm.addRobotChatResponse("Error ocurred, Please contact site owner and try again later ");

                    });
                
            }
        });
    };
</script>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Donate Plasma Save Life";
}
@model SahayogNepal.Models.ViewModels.HomeViewModel
<section class="header1 cid-s48MCQYojq mbr-fullscreen mbr-parallax-background" id="header1-f">



    <div class="mbr-overlay" style="opacity: 0.7; background-color: rgb(255, 181, 181);"></div>

    <div class="align-center container-fluid">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-12">
                <h1 class="mbr-section-title mbr-fonts-style mb-3 display-2"><strong>आफु पनि बचौ अरुलाई पनि बचाऔ&nbsp; &nbsp;</strong></h1>

                <p class="mbr-text mbr-fonts-style display-7">
                    Plasma from recovered COVID-19 patients is urgently needed across hospitals in Nepal.<br><br>
                    Register as<br>
                </p>
                <div class="mbr-section-btn mt-3"><a class="btn btn-success display-4" href="/Donor">Donor (दाता)&nbsp;</a> <a class="btn btn-success-outline display-4" href="/Patient">Patient (बिरामी) &gt;</a></div>
            </div>
        </div>
    </div>
</section>

<section class="content4 cid-sblhRf9bu0" id="content4-l">


    <div class="container">
        <div class="row justify-content-center">
            <div class="title col-md-12 col-lg-12">
                <h3 class="mbr-section-title mbr-fonts-style align-center mb-4 display-7">
                    <strong>
                        *Plasma therapy is an experimental COVID therapy. Before you register, please consult your doctor if this is required. Only patients with a case sheet from the doctor on duty will be matched.
                    </strong>
                </h3>
                <h4 class="mbr-section-subtitle align-center mbr-fonts-style mb-4 display-5"><div></div></h4>

            </div>
        </div>
    </div>
</section>

<section class="pricing1 cid-sblibZ9YWz" id="pricing1-n">
    <div class="container">
        <div class="row justify-content-center">
            <div class="card col-12 col-lg-6">
                <div class="card-wrapper">
                    <div class="card-box align-left">
                        <h6 class="card-title mbr-fonts-style mb-4 display-2">
                            <strong>Donors</strong>
                        </h6>
                        <ul class="list mbr-fonts-style mb-5 display-7">
                            <li class="item-wrap">Total Donors Registered: @Model.Donors</li>
                            @*<li class="item-wrap">Latest Donor Registered on: </li>*@
                        </ul>
                    </div>

                </div>
            </div>

            <div class="card col-12 col-lg-6">
                <div class="card-wrapper">
                    <div class="card-box align-left">
                        <h6 class="card-title mbr-fonts-style mb-4 display-2">
                            <strong>Patients</strong>
                        </h6>
                        <ul class="list mbr-fonts-style mb-5 display-7">
                            <li class="item-wrap">Total Patient Registered: @Model.Patients</li>
                            @*<li class="item-wrap">Latest Patient Registered on: </li>*@
                        </ul>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>

<section class="clients2 cid-sbwyWPXXe9" id="clients2-m">




    <div class="container">
        <h1 class="card-title mb-4 mbr-fonts-style">
            <strong>Supported By:</strong>
        </h1><br />
        <div class="row justify-content-center">

            <div class="col-sm-12 col-md-6 col-lg-6">
                <div class="card-wrapper">
                    <div class="img-wrapper text-center">
                        <a href="https://www.facebook.com/theyneedbloodpage/" target="_blank">
                            <img src="~/assets/images/theyneedblood.png" style="border-radius:50%;height:30vH;width:auto">
                        </a>
                    </div>
                    <div class="card-box align-center">

                        <h5 class="card-title mbr-fonts-style mb-3 display-5">
                            <strong>They Need Blood</strong>
                        </h5>
                    </div>
                </div>
            </div>
            <div class="col-sm-12 col-md-6 col-lg-6">
                <div class="card-wrapper">
                    <div class="img-wrapper text-center">
                        <a href="https://www.facebook.com/groups/1220011578350038/" target="_blank">
                            <img src="~/assets/images/plasmabanknepal.png" style="border-radius:50%;height:30vH;width:auto">
                        </a>
                    </div>
                    <div class="card-box align-center">

                        <h5 class="card-title mbr-fonts-style mb-3 display-5">
                            <strong>Plasma Bank Nepal</strong>
                        </h5>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>

Views/Home/PlasmaTherapy.cshtml
@{
    ViewData["Title"] = "Plasma Therapy";
}
<style>
    /* SECTION */
    .section {
        background-color: #fff;
        color: inherit;
        position: relative;
        padding: 90px 0;
        overflow: hidden;
    }

    .section-brief {
        font-size: 18px;
    }

    .section-heading {
        position: relative;
        padding-bottom: 20px;
        margin: 0 0 30px;
        font-family: "Montserrat", sans-serif;
        font-size: 24px;
        letter-spacing: 0.05em;
        text-transform: uppercase;
    }
</style>
<div class="container pt-lg-4">
    <div class="card col-sm-12">
        <div class="card-wrapper">
            <div class="card-box align-left">
                <h1 class="card-title mb-4 mbr-fonts-style">
                    <strong>WHAT IS PLASMA?</strong>
                </h1>
                 <p class="mbr-text mbr-fonts-style mb-5 display-7">
                    Plasma is the yellow liquid portion of blood comprised of water, salts, and proteins
                    which contains numerous proteins essential for proper functioning of the body.
                    insufficient levels of any one plasma protein prevents the body from carrying out vital
                    functions, causing a variety of chronic and life-threatening medical conditions.
                </p>
                <h1 class="card-title mb-4 mbr-fonts-style">A THERAPY ‘USED FOR OVER 100 YEARS’</h1>
                 <p class="mbr-text mbr-fonts-style mb-5 display-7">
                    This notion was first introduced in the late 19th century when physiologist Emil von
                    Behring and bacteriologist Kitasato Shibasaburou discovered that they could use
                    antibodies present in serum — another blood component — to fight the bacterial
                    infection diptheria.
                </p>
                 <p class="mbr-text mbr-fonts-style mb-5 display-7">
                    Since then, doctors have used passive antibody therapy, on and off, at least since
                    the 1930s to treat or prevent both&nbsp;bacterial and viral infections, including forms of
                    pneumonia, meningitis, and measles.
                </p>
                <h1 class="card-title mb-4 mbr-fonts-style">WHAT IS COVID-19 PLASMA AND HOW DOES IT HELP?</h1>
                 <p class="mbr-text mbr-fonts-style mb-5 display-7">
                    COVID-19 plasma is plasma collected from patients who have recovered from
                    COVID-19. The blood of people who have recovered from an infection contains
                    antibodies. Antibodies are molecules that have learned to recognize and fight the
                    pathogens, such as viruses, that have caused disease.
                </p>
                 <p class="mbr-text mbr-fonts-style mb-5 display-7">
                    Researchers hope that convalescent plasma can be given to people with
                    severe&nbsp;COVID-19&nbsp;to boost their ability to fight the virus. It also might help keep
                    people who are moderately ill from becoming more ill and experiencing&nbsp;COVID-
                    19&nbsp;complications.
                </p>
                 <p class="mbr-text mbr-fonts-style mb-5 display-7">
                    Convalescent plasma therapy may be helpful for people with&nbsp;COVID-19&nbsp;who aren't
                    helped by other treatments. Some people with&nbsp;COVID-19&nbsp;become very sick and
                    don't respond to other treatments or drugs. They often require mechanical
                    assistance, such as a ventilator, to breathe. These people also are in danger of
                    developing organ failure.
                </p>
                 <p class="mbr-text mbr-fonts-style mb-5 display-7">
                    It could also help other people who may have a higher risk of serious illness, such as
                    people with chronic medical conditions, for example, heart disease or diabetes, or
                    those who have weakened immune systems. Convalescent plasma could help these
                    people from getting sicker if they get&nbsp;COVID-19.
                </p>


                <h1 class="card-title mb-4 mbr-fonts-style">THE PROCEDURE</h1>
                 <p class="mbr-text mbr-fonts-style mb-5 display-7">
                    Before donated blood can be used, it must be tested for safety. It then goes through
                    a process to separate out blood cells so that all that's left is plasma with antibodies.
                </p>
                 <p class="mbr-text mbr-fonts-style mb-5 display-7">
                    A special machine separates the plasma and often the platelets from the donors’
                    blood sample. This process is called plasmapheresis. The remaining red blood cells
                    and other blood components are then returned to the body
                </p>
                 <p class="mbr-text mbr-fonts-style mb-5 display-7">The plasma is then carried to the patient.</p>
                 <p class="mbr-text mbr-fonts-style mb-5 display-7">
                    Before convalescent plasma therapy, the health care team prepares the patient for
                    the procedure. The health care team member inserts a sterile single-use needle
                    connected to a tube (intravenous, or IV, line) into a vein in one of the arms.
                    When the plasma arrives, the sterile plasma bag is attached to the tube and the
                    plasma drips out of the bag and into the tube. It takes about one to two hours to
                    complete the procedure.
                </p>
                <h1 class="card-title mb-4 mbr-fonts-style">WHO CAN DONATE COVID-19 PLASMA?</h1>
                 <p class="mbr-text mbr-fonts-style mb-5 display-7">
                    In addition to meeting the donor eligibility criteria, donors must have had a prior
                    infection of COVID-19 and must have recovered from symptoms at least 14 days
                    prior to donation. In addition they should:
                </p>
                <ul>
                    <li>Have had symptoms like breathing problem, cough, cold, fever, body ache.</li>

                    <li>The stronger the symptoms, the stronger the antibodies</li>
                    <li>Not have had any children (women only).</li>
                    <li>Not have diabetes.</li>
                    <li>Not have high blood pressure.</li>
                    <li>Not be over the age of 65.</li>

                </ul>
                 <p class="mbr-text mbr-fonts-style mb-5 display-7" >
                    Source: <a href="https://www.dhoondh.com/plasma-therapy">Dhoondh.com</a><br />
                    NOTE: THIS IS INFORMATION COLLATED FROM PUBLICLY AVAILABLE
                    WEBSITES.
                    WE ARE NOT, NOR DO WE CLAIM TO BE, PROPONENTS NOR ANY
                    AUTHORITY ON THIS PROCEDURE.
                    <br>
                    PLEASE CONSULT YOUR DOCTOR FOR
                    COMPLETE DETAILS.
                </p>
            </div>

        </div>
    </div>
</div>

Views/Home/SahayogiHaath.cshtml
@{
    ViewData["Title"] = "SahayogiHaath";
}
<style>
    .custab {
        border: 1px solid #ccc;
        padding: 5px;
        margin: 5% 0;
        box-shadow: 3px 3px 2px #ccc;
        transition: 0.5s;
    }

        .custab:hover {
            box-shadow: 3px 3px 0px transparent;
            transition: 0.5s;
        }
</style>
    <div class="container" style="min-height:70vH">
        <div class="row col-sm-12 col-md-offset-2 custyle">
            <div class="card-box align-left">
                <h1 class="card-title mb-4 mbr-fonts-style">
                    <strong>सहयोगी हातहरुलाई नमन</strong><br />
                </h1>
                <p class="mbr-text mbr-fonts-style mb-5 display-7">
                    SahayogNepal.org is a mission for social cause. Please support us<br />
                    Esewa: 9843178564 <br />
                    Khalti: 9843178564 <br />
                    Track of every Donation and Expense can be found on our github repo.
                </p>
            </div>
            <table class="table table-striped custab">
                <thead>
                    <tr>
                        <th>S.N.</th>
                        <th>Name</th>
                        <th>Type</th>
                        <th>Worth Amount</th>
                    </tr>
                </thead>
                <tr>
                    <td>1</td>
                    <td><a href="https://www.babal.host" target="_blank">babal host</a></td>
                    <td>Domain</td>
                    <td>Nrs. 1350</td>
                </tr>

            </table>
            </div>
        </div>

Views/Patient/Index.cshtml
@{
    ViewData["Title"] = "Patient Registration";
}

<style>
    #cf-context {
        width: 70vw;
        height: 70vh;
    }

    #form {
        height: 0px;
        overflow: hidden;
    }
</style>
<div class="container">

    <form id="form" cf-form">
        <cf-robot-message cf-questions="We are doing our level best to find matching donors. We will alert you when we find a suitable match."></cf-robot-message>
        <cf-robot-message cf-questions="Please remember time is of the essence for you so please diligently continue your search through all other options."></cf-robot-message>
        <cf-robot-message cf-questions="Please do not fill out this form with multiple contact details for the same patient."></cf-robot-message>

        <input type="text" name="name" cf-questions="What is the patient's name?">
        <input type="number" name="mobile" cf-questions="What is your mobile number?">
        <input type="number" name="age" cf-questions="How old is the patient?">
        <input cf-questions="What is the patient's gender?" type="radio" name="gender" value="female" cf-label="female">
        <input type="radio" name="gender" value="male" cf-label="male">
        <input type="radio" name="gender" value="other" cf-label="other">
        <input type="text" name="city" cf-questions="What is your current address?">
        <input cf-questions="What's the patient blood group?" type="radio" name="blood" value="A+" cf-label="A+">
        <input type="radio" name="blood" value="A-" cf-label="A-">
        <input type="radio" name="blood" value="B+" cf-label="B+">
        <input type="radio" name="blood" value="B-" cf-label="B-">
        <input type="radio" name="blood" value="O+" cf-label="O+">
        <input type="radio" name="blood" value="O-" cf-label="O-">
        <input type="radio" name="blood" value="AB+" cf-label="AB+">
        <input type="radio" name="blood" value="AB-" cf-label="AB-">
        <input type="text" name="hospital" cf-questions="Which hospital is the patient in">
        <input cf-questions="Do you have case sheet from doctor?" type="radio" name="hasCaseSheet" value="true" cf-label="Yes">
        <input type="radio" name="hasCaseSheet" value="false" cf-label="Not Yet">
        <cf-robot-message cf-questions="By submitting this form"></cf-robot-message>
        <cf-robot-message cf-questions="I confirm that the information I have provided in here is complete and accurate to the best of my knowledge."></cf-robot-message>
        <cf-robot-message cf-questions="I confirm that I wish to share the information provided in here for the exclusive purpose(s) of matching with donors from the database of donors registered with sahayogNepal and sharing this information directly and solely with the matched donors."></cf-robot-message>
        <input cf-questions=Confirmation? name="confirm" cf-label="Yes submit this data" type="radio" value="0">

    </form>
    <div id="cf-context" role="cf-context" cf-context></div>
    <!-- partial -->

</div>
<script src='https://cdn.jsdelivr.net/gh/space10-community/conversational-form@latest/dist/conversational-form.min.js'></script>
<script>
    window.onload = function () {
        var conversationalForm = window.cf.ConversationalForm.startTheConversation({
            formEl: document.getElementById("form"),
            context: document.getElementById("cf-context"),
            submitCallback: function () {
                var formData = conversationalForm.getFormData();
                var formDataSerialized = conversationalForm.getFormData(true);
                console.log("Formdata:", formData);
                console.log("Formdata, serialized:", formDataSerialized);
                $.post("/patient/submitPatientData/", { patientData: formDataSerialized })
                    .done(function () {
                        conversationalForm.addRobotChatResponse("Thank you, we will contact you once we find suitable match.");
                    }).fail(function () {
                        conversationalForm.addRobotChatResponse("Error ocurred, Please contact site owner and try again later ");

                    });

            }
        });
    };
</script>